export const REST_COMMANDS = {
  REQ_POST_LOGIN: 1,
  REQ_GET_ALL_POSTS: 2,
  REQ_GET_SEARCH_EXPLORE: 3,
  REQ_GET_ALL_EVENTS: 4,
  REQ_GET_PERSONAL_CHAT:5,
  REQ_GET_PERSONAL_RECENT_CHAT:6,
  REQ_GET_USER_PROFILE: 7,
  REQ_GET_EXPLORE_GROUPS: 8,
  REQ_GET_EXPLORE_USERS: 9
};
